# Generated by Django 4.1.5 on 2023-03-03 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_remove_entregable_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
